service: instagrammer
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 512
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        - "arn:aws:s3:::${env:AWS_BUCKET_NAME}/*"

functions:
  create-post:
    handler: src/handlers/createPost.run
    events:
      - schedule: rate(12 hours)

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
